# Etapa 1: Construcción (Build)
FROM node:20-slim AS build 
WORKDIR /app

# Instalamos pnpm globalmente
RUN npm install -g pnpm

# Copiamos los archivos de dependencias
# Incluimos pnpm-lock.yaml para asegurar las versiones exactas
COPY package.json pnpm-lock.yaml* ./

# Instalamos las dependencias usando pnpm
RUN pnpm install --frozen-lockfile

# Copiamos el resto del código y generamos los archivos de producción
COPY . .
RUN pnpm run build --configuration=production

# Etapa 2: Servidor Web (Producción)
FROM nginx:alpine
# Ajusta 'nombre-de-tu-app' por el que aparezca en tu carpeta /dist
COPY --from=build /app/dist/nombre-de-tu-app /usr/share/nginx/html

# Recomendado: Copiar configuración de Nginx para evitar errores 404 al refrescar
# COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]